# Info about the map:

borderColour: { r: 0, g: 0, b: 0 }
wraparound: True


# Nations configuration. List of names & colour.

nations:
  foo: { r: 255, g: 0, b: 0 }
  bar: { r: 0, g: 255, b: 0 }
  baz: { r: 0, g: 0, b: 255 }


# Provinces. List of province number & owner

provinces:
  1: foo
  2: foo
  3: bar
  4: baz
  5: foo
  6: bar
  7: baz
  8: baz
  9: bar
